<?php
function challengemb_theme($existing, $type, $theme, $path) {
    return [
      // Name of the theme hook. This is used in the controller to trigger the hook.
      'challengemb' => [
        'render element' => 'children',
        'template' => 'challengemb',
        'variables' => [
          'text' => 'Yet another default text.',
          'number' => 0
        ],
      ],
    ];
  }

function challengemb_preprocess_html(&$variables) {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
    $variables['attributes']['class'][] = 'mb-node-type-' . str_replace('_', '-', $node->bundle());
  }
}

function challengemb_preprocess_page(&$variables)
{
  $variables['#attached']['drupalSettings']['challengemb']['sitename'] =  \Drupal::config('system.site')->get('name');
}